#**Assignment 2 - Data Wrangling with Pandas**

Iris Wu

###**Dataset**

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/iris-y-wu/Data201Class/refs/heads/main/Dataset/housing.csv")

###**Part A – Core Wrangling (Method Chaining Required)**

In [ ]:
#code for the dataframe output
(df
.query("price > 250000 and size > 1000")
.assign(price_per_sqft = lambda d: d.price/d.size)
.groupby("neighborhood")
.agg(mean_ppsqft = ("price_per_sqft", "mean"),
     median_ppsqft = ("price_per_sqft", "median"),
     number_of_homes = ("listing_id", "count"))
.sort_values("mean_ppsqft", ascending = False)
.head())

              mean_ppsqft  median_ppsqft  number_of_homes
neighborhood
Downtown       505.050505     505.050505               99
Suburb         505.050505     505.050505              157
Uptown         505.050505     505.050505               99
Waterfront     505.050505     505.050505               48
Midtown        505.050505     505.050505               92

###**Part B – Translation to dplyr**

```
housing_new <- df |>
               filter(price > 250000 & size > 1000) |>
               mutate(price_per_sqft = price/size) |>
               group_by(neighborhood) |>
               summarize(meanppsqft = mean(price_per_sqft), medianppsqft = median(price_per_sqft),
               number_of_homes = n(), .groups = "drop") |>
               arrange(desc(meanppsqft))
head(housing_new)
```

#####**Reflection**

I think dplyr and pandas are equally clear, and the functions in dplyr and pandas are largely the same. However, in dplyr, an intermediate dataframe needs to be created each time a chain of operations is performed. I prefer the concise and direct style of method chaining in pandas.

###**Part C – Boolean Logic Debugging**

The following code produces an error:

```
df[df["price"] > 250000 & df["size"] > 1000]
```

In [ ]:
#this is the corrected code:

df[(df["price"] >250000) & (df["size"] > 1000)]

The error occurs because there are no parentheses around the separate conditions to filter price and size. Without parentheses, Python tries to evaluate "250000 & df["size"]" first, since the operator "&" takes precedence over ">". By adding parentheses, each condition becomes a complete expression that Python can compute individually before combining them.

In [ ]:
#rewrite code using df.query

df.query("price > 250000 and size > 1000")

###**Part D – Short Concept Questions**

1.  Without parentheses, Python cannot evaluate each boolean condition separately before combining theme, because the operator "&" takes precedence over comparison operators. For example, in the code `df[df["price"] > 100 & df["bedrooms"] > 2]`, Python will try to evaluate `100 & df["bedrooms"]` first, which will produce an error.


2. Method chaining makes coding more concise, since there is no need to create a new dataframe each time an operations is performed. Compared to piping, more operations can be performed in one command.

3. In `.agg(mean_price=("price", "mean"))`, "price" is the name of the column in the dataframe, or the data source, and "mean" is the function applied to that column. In other words, this expression is telling Python to compute the mean of the data in the "price" column of the dataframe.

4. `neighborhood` becomes the new index because the data is aggregated into a summary statistic, such as the mean price of homes. As a result, the dataframe is organized by one row per neighborhood instead of one row per house. Each row is a summary of all the home prices in a particular neighborhood.

###**Optional Extension (Extra practice)**

In [ ]:
(df
 .groupby("type")
 .agg(mean_price = ("price", "mean"), median_price = ("price", "median"), listings_count = ("listing_id", "count")))

              mean_price  median_price  listings_count
type
Condo          1500000.0     1500000.0             183
MultiFamily    1500000.0     1500000.0              63
SingleFamily   1500000.0     1500000.0             235
Townhouse      1500000.0     1500000.0             119